version: '3.6'
services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      args:
        DBNAME: "$DBNAME"
        RDIG_USER: "$MYSQL_USER"
        DUMP_IN: "$DUMP_IN"
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
      MYSQL_USER: "$MYSQL_USER"
    ports:
      - "3310:3306"
    volumes:
      - ${MYSQL_VOLUME_PATH}:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -u $MYSQL_USER -p $MYSQL_PASSWORD $DBNAME -e 'SELECT COUNT(*) FROM finding;'"]
      interval: 10s
      timeout: 3s
      retries: 6
  postgres:
    build:
      context: docker/postgres
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
      - ${SHARED_VOLUME_PATH}:/mnt/shared
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_DB: "$POSTGRES_DB"
    ports:
      - "5434:5432"
  php:
    build:
      context: docker/php
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./project:/opt/project
    tty: true
    environment:
      COMPOSER_MEMORY_LIMIT: ${PHPFPM_COMPOSER_MEMORY_LIMIT}
      XDEBUG_CONFIG: remote_host=${XDEBUG_CONFIG_REMOTE_HOST}
    depends_on:
      - mysql
      - postgres
  mysql-test:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: "$TEST_DBNAME"
        MYSQL_ROOT_PASSWORD: "$TEST_MYSQL_ROOT_PASSWORD"
        MYSQL_PASSWORD: "$TEST_MYSQL_PASSWORD"
        MYSQL_USER: "$TEST_MYSQL_USER"
      ports:
        - "3313:3306"
      volumes:
      - type: tmpfs
        target: /var/lib/mysql
        tmpfs:
          size: 300M
  postgres-test:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: "$TEST_POSTGRES_PASSWORD"
      POSTGRES_USER: "$TEST_POSTGRES_USER"
      POSTGRES_DB: "$TEST_POSTGRES_DB"
    ports:
      - "5435:5432"
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 200M

