doctrine:
    dbal:
        default_connection: mysql
        connections:
            mysql:
                # configure these for your database server
                url: '%env(resolve:MYSQL_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
#            postgres:
#                url: '%env(resolve:POSTGRES_DATABASE_URL)%'
#                driver: 'pdo_pgsql'
#                server_version: '12'
#                charset: utf8

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: mysql
        entity_managers:
            mysql:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: mysql
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/mapping/orm'
                        prefix: 'App\Entity'
                        alias: App
